run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - testdata
    - vendor

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - exportloopref  # Deprecated in Go 1.22+

linters-settings:
  dupl:
    threshold: 150
  funlen:
    lines: 250
    statements: 100
  gocyclo:
    min-complexity: 25
  goimports:
    local-prefixes: github.com/ideamans/go-png-meta-web-strip
  lll:
    line-length: 140
  misspell:
    locale: US
